### ISSUE TITLE
[ ] not Recognizing In Python

### ISSUE THREAD

**Issue by baldaudhanoriya** [Pustelto/Bracketeer#11]
Everything Is working good In C language 
But in python  Shift+Ctrl+Alt+K  Shortcut Only  Swap brackets ( ) and { } it's not changing [ ]

**Comment by Pustelto** [comment]
Hi @baldaudhanoriya thanks for the info. Can you please send me a snippet of the python code which is not working  as mentions above? I will have a look in to this.

**Comment by baldaudhanoriya** [comment]
I'm trying to change List comprehension---- [1 for x in a] ----- to----- (1 for x in a)-------but the error is    No brackets to modify found.
![image](https://user-images.githubusercontent.com/47846908/58961655-3d685480-87c7-11e9-895b-b0b450d4ed4e.png)

**Comment by Pustelto** [comment]
Thanks @baldaudhanoriya will have a look into it during the weekend.

**Comment by Pustelto** [comment]
hi @baldaudhanoriya I have added support for square bracketes in python.

**Comment by baldaudhanoriya** [comment]
thank you
