### ISSUE TITLE
Add macOS keybindings to README/details page

### ISSUE THREAD

**Issue by blakebuthod** [Pustelto/Bracketeer#17]
Noticed the keybindings are full of `Alt` which I don't have on my keyboard

**Comment by Pustelto** [comment]
Hi @blakebuthod didn't know there are some Macs without an alt key (it's on my macbook pro so I thought it will be everywhere). I mostly select quite wild keybinding to avoid conflicting with other packages/shortcuts. But you can easily change the bindings in the settings.

- open command pallet and go to `Preferences: Open Keyboard Shortcuts`
- then search for `bracketeer` and there you can change the shortcuts to whatever suits you best. 

Everyone has preferred keyboard layout so it's impossible to make it perfect for everyone.

Hope this help.
