### ISSUE TITLE
Running the contributed command: COMMAND_NAME failed.

### ISSUE THREAD

**Issue by gvmohzibat** [Pustelto/Bracketeer#27]
Running every command results in this error:
Running the contributed command: COMMAND_NAME failed.

I'm using the latest version of VS Code. Tried every command in .js and .ts files.

I switched to version 1.2.4 and it works. Version 1.2.5 doesn't work

**Comment by Pustelto** [comment]
Oh thanks for info. Will fix it asap

**Comment by Pustelto** [comment]
Hi @gvmohzibat I fix it, sorry for the troubles. I somehow forget to merge changes in 1.2.4 to master and thus reintroduce old bug in 1.2.5. Should be ok in current version (1.2.7). Please give it a try and if there are still some issues let me know.

Thanks
