### ISSUE TITLE
Swap quotes gets stuck on backticks in Ruby

### ISSUE THREAD

**Issue by noniq** [Pustelto/Bracketeer#31]
Same as in #24, but in Ruby:

If I have text wrapped in double quotes (i.e. `"text"`) and try to swap quotes it cycles through to backticks correctly (\``text`\`), but if I try to swap quotes again it doesn't work (“No quotes to modify found.”) instead of cycling to single quotes (e.g. `'text'`).

**Comment by Pustelto** [comment]
Hi @noniq, thanks for submitting issue. Could you please send me some small code sample on which I could test it? Will try to fix it. Thanks

**Comment by noniq** [comment]
Any Ruby file containing a string will do, for example:

```ruby
puts "foobar"
```

As a workaround I added the following to `language-definitions.json`:

```json
  "ruby": {
    "quotes": ["\"", "'"],
    "brackets": ["()", "[]", "{}"],
    "string_tokens": ["string"],
    "bracket_tokens": ["punctuation"]
  }
```

This seems to work correctly so far, but I’m not sure if it’s really correct (I simply copied the settings from the entry for PHP).

**Comment by Pustelto** [comment]
Yeah it is. Not a ruby dev, so maby a silly question - are backticks valid quotes for strings? Or there should be only `"` and `'`?

**Comment by noniq** [comment]
They are kind of valid: Text in backticks gets executed as subprocess and replaced by its return value (like in Bash and similar shells).

So I think technically they don’t count as “normal” quotes. I can’t think of many situations where I want to change a quoted string into a command to be executed or vice-versa. Better exclude them from quote-swapping.

**Comment by Pustelto** [comment]
Hi @noniq I have add your ruby language definition to the Bracketeer. It will be in the next release (this Sunday). PR #44
