### ISSUE TITLE
Same keyboard shortcut for selection quotes and brackets contents

### ISSUE THREAD

**Issue by smjure** [Pustelto/Bracketeer#33]
Similarly as in issue #30, it would be great to be able to define one keybinding for selection of the content between quotes and brackets. 

Thank you for the great job.

**Comment by Pustelto** [comment]
Closing since it's duplicate of #30 as you mentions @smjure. So for any related info or comments please watch this issue. Don't have much time for Bracketeer right now so not sure how fast I can get it done.
