### ISSUE TITLE
BracketPair Settings: Prism.languages.insertBefore is not a function

### ISSUE THREAD

**Issue by yubaoquan** [Pustelto/Bracketeer#38]
Thrown from `onDidChangeNotification`.

By the way, is this extension in maintaining?

**Comment by Pustelto** [comment]
Hi can you please provide exact info how to duplicate the issue? That would help me a lot.

As for the maintenance. I don't have much time at the moment but I plan to keep on maintaining it as I use it on daily basis. Will try focus on it more in the upcomming month.

**Comment by yubaoquan** [comment]
Step to reproduce:
1. Open a folder with no file opened; (Must ensure there are no files opened at first time the vscode load the folder)
2. Click on the file tree to open a js file;
3. Click in a pair of brackets;
4. Open command plattee select `replace brackets with`, select a bracket option;
5. Click on the file tree to open a vue file; // the first error will report 'BracketPair Settings: Prism.languages.extend is not a function'
6. In the vue file , exec the command `replace brackets with`; // the second error reports 'Command 'Bracketeer: Replace brackets with...' resulted in an error (Cannot read property 'rest' of undefined)'


You can first open vue file and then open js. The files opening order does not matter.

I can found the earliest cause of error is in `getParseLanguage`, after the first error happens, `js` and `vue` properties were removed from `Prism.languages`. So `parseBrackets` function got a undefined prismLang.

**Comment by Pustelto** [comment]
Ok, feel free to open an issue when you found some reproducible error. There may be some edge cases when it not work very well. Unfortunatelly prism package has it's limitations.
