### ISSUE TITLE
Bracketeer is installed and enabled, but the commands aren't available

### ISSUE THREAD

**Issue by REDawson** [Pustelto/Bracketeer#46]
when I use the keyboard shortcuts i get a toaster that says: "command 'bracketeer.<command>' not found". 

I can find the command when searching with the > filter in VSCode, but when i run from there i get the same message. 

I love bracketeer and was happily using it for about a week before this started happening. I've tried uninstalling, disabling, and a host of other easy tech tips to get it working again and nothing works. 

please fix

**Comment by Pustelto** [comment]
Hi @REDawson what version of bracketeer and Vs code are you using? Have you tried some older versions of bracketeer if the problem is there as well? Is this happening with all bracketeer commands or with just few? What language?

I will try to help, but I need more info.

**Comment by REDawson** [comment]
Hi @Pustelto, thanks for getting back to me. I went to answer your questions and updated VSCode to 1.51.1. After updating, reloading, then going to the Bracketeer extension page and reloading from there as well, it started working again. 

With the latest Bracketeer (1.3.1) and latest VSCode (1.51.1) I no longer have this issue

Thanks for the help! This is a great extension and I'm excited to start using it again.
