### ISSUE TITLE
How can I change the keyboard shortcuts?

### ISSUE THREAD

**Issue by futuremotiondev** [Pustelto/Bracketeer#61]
Question is title. Is there a config I can edit to change the various shortcuts?

Thanks!

**Comment by Pustelto** [comment]
Hi,

sure there are. Just go to the keyboard settings and type bracketeer. It will show you available commands and you can bind them to whatever work best for you. 

The commands are:
```
bracketeer.removeBrackets
bracketeer.swapBrackets
bracketeer.changeBracketsTo
bracketeer.selectBracketContent
bracketeer.swapQuotes
bracketeer.removeQuotes
bracketeer.changeQuotesTo
bracketeer.selectQuotesContent
```

![image](https://user-images.githubusercontent.com/10606260/164991383-eabafd3b-8274-46dd-9d6c-67da17eab83b.png)
