### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by atscripter** [Pustelto/Bracketeer#7]
@Pustelto Just wanted to say thank you for an awesome extension!

The built-in "expand select" is useless as it only works when there are no special characters in the string you are trying to select. The "Quick and Simple" text selection extension has the same problem and I couldn't find any solution for such basic, routine task. I stumbled on "Bracketeer" while searching the marketplace for keyword "macro" in an attempt to find a macro extension to enable me to record and replay quote selection. Luckily this came up and Bracketeer just killed it.

Keep up the good work 👍

**Comment by Pustelto** [comment]
Hey, @atscripter thanks for feedback, I'm glad to hear it helped you. Had same issue, that's why I created Bracketeer. Feel free to get in touch if you encounter any issues. I didn't have much time lately to work on it. But I will try to keep it in good shape.
